# top level
# ------------------
site_name: AuroraX Documentation
site_url: https://docs.aurorax.space
repo_url: https://github.com/aurorax-space
edit_uri: "docs/edit/main/docs/"


# theme settings
# ------------------
theme:
  name: material
  logo: img/logo.svg
  favicon: img/logo.svg
  palette:
    - scheme: default
      primary: black
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.suggest
    - search.highlight
markdown_extensions:
  - meta
  - toc:
      permalink: true
      toc_depth: 3
  - markdown.extensions.codehilite:
      guess_lang: false
  - pymdownx.superfences:
extra:
  analytics:
    provider: google
    property: G-284760515
  social:
    - icon: fontawesome/solid/globe
      link: https://aurorax.space
      name: AuroraX website
    - icon: fontawesome/brands/github-alt
      link: https://github.com/aurorax-space
      name: Source code on Github
extra_css:
  - stylesheets/extra.css


# navigation
# ------------------
nav:
  - Home: index.md
  - About the Data: 
    - Overview: about_the_data/overview.md
    - What metadata is in the AuroraX database?: about_the_data/metadata_in_aurorax.md
    - Data Categories: about_the_data/categories.md
    - Instrument Descriptions: 
      - Ground-based: about_the_data/instruments/ground.md
      - Space-based: about_the_data/instruments/space.md
    - Data Availability: about_the_data/availability.md
    - Data Policy: about_the_data/policy.md
    - Recommended Standards: about_the_data/standards.md
  - Machine Learning:
    - Overview: ml/overview.md
    - Models:
      - UCalgary Cloud: ml/models/ucalgary_cloud.md
      - UCalgary APA: ml/models/ucalgary_apa.md
      - Clausen OATH: ml/models/clausen_oath.md
  - RESTful API:
    - Overview: api/overview.md
    - Basic Usage: api/basic_usage.md
    - Advanced Usage: 
      - Data Availability and Stats: api/advanced_usage/availability_and_stats.md
    - Authentication Strategy: api/authentication_strategy.md
  - Python:
    - PyAuroraX:
      - Overview: python_libraries/pyaurorax/overview.md
      - Installation: python_libraries/pyaurorax/installation.md
      - Basic Usage: python_libraries/pyaurorax/basic_usage.md
      - Advanced Usage:
        - Authentication: python_libraries/pyaurorax/advanced_usage/authentication.md
        - Advanced conjunction searches: python_libraries/pyaurorax/advanced_usage/advanced_conjunctions.md
        - Searches with metadata filters: python_libraries/pyaurorax/advanced_usage/searches_with_metadata_filters.md
        - Managing data: python_libraries/pyaurorax/advanced_usage/managing_data.md
        - Data Availability and stats: python_libraries/pyaurorax/advanced_usage/availability_and_stats.md
      - API reference: python_libraries/pyaurorax/api_reference/aurorax/index.html
#    - aurorax-asilib:
#      - Overview: python_libraries/aurorax_asilib/overview.md
  - IDL:
      - Overview: idl_libraries/idl_aurorax/overview.md
